- name: "Copy compiled backend app"
  become: true
  copy:
    src: dist.tar.gz
    dest: /home/ubuntu

- name: "Unzip backend files to correct directory"
  shell: |
      cd /home/ubuntu
      tar -xzvf dist.tar.gz

- name: "Copy package.json"
  become: true
  copy:
    src: package.json
    dest: /home/ubuntu/dist

- name: "Install dependencies for project"
  shell: |
    cd /home/ubuntu/dist
    npm install

- name: Start PM2
  shell: |
    cd /home/ubuntu/dist
    pm2 start main.js --name udapeople-backend