- name: "Copy compiled backend app"
  become: true
  copy:
    src: backend.tar.gz
    dest: /home/ubuntu

- name: "Unzip backend files to correct directory"
  shell: |
      cd /home/ubuntu
      tar -xzvf backend.tar.gz
      rm -rf backend.tar.gz

- name: Install Node
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Build Node
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: Start PM2
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start